### ISSUE TITLE
boolean variables from existing node group classes are reported as string not Boolean

### ISSUE THREAD

**Issue by abuxton** [puppetlabs/puppetlabs-node_manager#28]
i.e
#puppet resource node_group 'PE Infrastructure' -e
node_group { 'PE Infrastructure':
  ensure               => 'present',
  classes              => {
                          'puppet_enterprise' => {
                               <TRUNCATED>...,
                              'use_application_services' => 'true', #should be 'use_application_services' => true,
                              }
                            },
  environment          => 'production',
  override_environment => 'false',
  parent               => 'All Nodes',
} 
Notice: Compiled catalog for rm101puppetm.room101.com in environment production in 0.22 seconds
Info: Applying configuration version '56b9af74a231f1f22b3cc53664ed2aaf3c72cbbd'
Notice: /Stage[main]/Main/Node_group[PE Infrastructure]/classes: classes changed {"puppet_enterprise"=>{<TRUNCATED>...,'use_application_services' => 'true'}} to '{"puppet_enterprise"=>{<TRUNCATED>..., "use_application_services"=>"true"}}'

The override_environment => 'false', or override_environment => 'true' is not affected.
but post change to the node group with the resource from puppet resource node_group 'PE Infrastructure' -e 
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Class[Puppet_enterprise]: parameter 'database_ssl' expects a Boolean value, got String on node <removed>
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

Issue ony affected class variables.

**Comment by WhatsARanjit** [comment]
`puppet resource` always quotes everything.  It's a problem in general.

https://tickets.puppetlabs.com/browse/PUP-4078
