### ISSUE TITLE
Failure to apply node_group via Bolt

### ISSUE THREAD

**Issue by kreeuwijk** [puppetlabs/puppetlabs-node_manager#42]
When using Puppet Bolt to apply a node_group to a PE master, the module is looking in the wrong place for the classifier.yaml. The error is `Failed to apply catalog: Could not find file /tmp/d20181217-32970-1e9axsa/conf/classifier.yaml`

The following code was applied with Bolt:
```
node_group { 'Workshop':
  ensure               => 'present',
  classes              => {
    'role::workshop' => {},
  },
  environment          => 'production',
  override_environment => 'false',
  parent               => 'All Nodes',
  rule                 => ['or',
    ['=', 'name', 'master.inf.puppet.vm']
  ],
}
```
The above code was saved as workshop_nodegroups.pp and applied with Bolt like this:
`bolt apply ./workshop_nodegroups.pp --nodes <pe_master> [connection settings]`

**Comment by cdenneen** [comment]
@kreeuwijk how did you solve this?

**Comment by jessereynolds** [comment]
This issue needs reopening as it's still a problem. 

node_manager's node_group resource and the underlying https provider for it are incompatible with bolt apply without modifying the source code (it looks for classifier.yaml in a temporary confdir that bolt manages during the apply catalog step whereas that file resides in the actual puppet confdir `/etc/puppetlabs/puppet/'
