### ISSUE TITLE
Releases 0.7.2 and 0.7.3 are missing tags

### ISSUE THREAD

**Issue by seanmil** [puppetlabs/puppetlabs-node_manager#51]
Neither the 0.7.2 nor 0.7.3 release were tagged in Git. Some of us use/deploy modules based off of Git tags. Thanks!

**Comment by WhatsARanjit** [comment]
Created 2 new tags retro-mapped to the commits. Thanks for catching this.

https://github.com/WhatsARanjit/puppet-node_manager/tags
